import type { Metadata } from "next";
import { Inter, DM_Sans, Wix_Madefor_Display } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/classNames";


const sans = DM_Sans({
  subsets: ["latin"],
  variable: '--font-sans',
  display: 'swap'
});
const display = Wix_Madefor_Display({
  subsets: ["latin"],
  variable: '--font-display',
  display: 'swap'
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(sans.variable, display.variable)}>
      <body >{children}</body>
    </html>
  );
}
