import type { Metadata } from "next";
import { Inter, Outfit, Wix_Madefor_Display, DM_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "./component/utils/classNames";


const inter = Inter({ subsets: ["latin"] });

const sans = DM_Sans({ 
  subsets: ["latin"] ,
  variable: '--font-sans',
  display: 'swap'
});

const display = Wix_Madefor_Display({
  subsets: ["latin"],
  variable: '--font-display',
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('font-display',display.variable, sans.variable )}>{children}</body>
    </html>
  );
}
